FROM node:20-alpine AS dependencies

WORKDIR /app

COPY package.json package-lock.json /app/
RUN npm ci

FROM dependencies AS development

COPY . /app

EXPOSE 5173

FROM dependencies AS build

COPY . /app
RUN npm run build

FROM nginx:1.27-alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
