# Generated by Django 5.1.7 on 2026-04-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='httrserieswell',
            options={'ordering': ['series_id', 'dose_level', 'well_id'], 'verbose_name': 'HTTr series well', 'verbose_name_plural': 'HTTr series wells'},
        ),
        migrations.AlterModelOptions(
            name='httrwell',
            options={'ordering': ['study_metadata_id', 'plate_id', 'well_row', 'well_column'], 'verbose_name': 'HTTr well', 'verbose_name_plural': 'HTTr wells'},
        ),
        migrations.AlterModelOptions(
            name='pod',
            options={'ordering': ['series_id', 'metric_id'], 'verbose_name': 'POD', 'verbose_name_plural': 'PODs'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['study_metadata_id', 'chemical_sample_id', 'id'], 'verbose_name': 'series', 'verbose_name_plural': 'series'},
        ),
        migrations.AlterModelOptions(
            name='studywarehousemetadata',
            options={'ordering': ['study_name', 'id'], 'verbose_name': 'study warehouse metadata', 'verbose_name_plural': 'study warehouse metadata'},
        ),
    ]
