# Generated by Django 5.1.7 on 2026-04-28 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_alter_httrserieswell_options_alter_httrwell_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(blank=True, max_length=255)),
                ('source_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='planned', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_rejected', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('ext', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiling_import_batches', to=settings.AUTH_USER_MODEL)),
                ('study_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='profiling.studywarehousemetadata')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'verbose_name': 'import batch',
                'verbose_name_plural': 'import batches',
            },
        ),
        migrations.CreateModel(
            name='StudyDataResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('raw', 'Raw data'), ('intermediate', 'Intermediate data'), ('feature', 'Feature data'), ('signature', 'Signature data'), ('metadata', 'Metadata'), ('manifest', 'Manifest'), ('publication', 'Publication'), ('supporting', 'Supporting data'), ('other', 'Other')], max_length=30)),
                ('storage_kind', models.CharField(choices=[('local_path', 'Local path'), ('network_path', 'Network path'), ('object_uri', 'Object URI'), ('url', 'URL'), ('accession', 'Accession'), ('other', 'Other')], max_length=30)),
                ('display_name', models.CharField(max_length=255)),
                ('uri', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('file_format', models.CharField(blank=True, max_length=100)),
                ('checksum_algorithm', models.CharField(blank=True, max_length=50)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('archived', 'Archived'), ('missing', 'Missing'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('ext', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_resources', to='profiling.studywarehousemetadata')),
            ],
            options={
                'ordering': ['study_metadata_id', 'resource_type', 'display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatchResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('reference', 'Reference'), ('qa', 'QA'), ('other', 'Other')], default='input', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='profiling.importbatch')),
                ('data_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_links', to='profiling.studydataresource')),
            ],
            options={
                'verbose_name': 'import batch resource',
                'verbose_name_plural': 'import batch resources',
                'ordering': ['import_batch_id', 'role', 'data_resource_id'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['study_metadata', 'status'], name='import_batch_study_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studydataresource',
            index=models.Index(fields=['study_metadata', 'resource_type'], name='resource_study_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='studydataresource',
            constraint=models.UniqueConstraint(fields=('study_metadata', 'uri'), name='unique_resource_uri_per_study'),
        ),
        migrations.AddConstraint(
            model_name='studydataresource',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__isnull', True), ('size_bytes__gte', 0), _connector='OR'), name='study_resource_size_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='importbatchresource',
            constraint=models.UniqueConstraint(fields=('import_batch', 'data_resource'), name='unique_resource_per_import_batch'),
        ),
    ]
