# Generated by Django 5.1.7 on 2026-05-01 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0003_importbatch_studydataresource_importbatchresource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="study_metadata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_batches",
                to="profiling.studywarehousemetadata",
            ),
        ),
        migrations.AlterField(
            model_name="studydataresource",
            name="study_metadata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_resources",
                to="profiling.studywarehousemetadata",
            ),
        ),
        migrations.CreateModel(
            name="ImportAliasMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_role", models.CharField(choices=[("metadata", "Metadata"), ("contrasts", "Contrasts"), ("count", "Count data")], max_length=30)),
                ("scope", models.CharField(choices=[("study", "Study"), ("sample", "Sample"), ("resource", "Resource")], default="sample", max_length=30)),
                ("canonical_target", models.CharField(max_length=255)),
                ("source_column", models.CharField(max_length=255)),
                ("transforms", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("import_batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alias_maps", to="profiling.importbatch")),
            ],
            options={
                "ordering": ["import_batch_id", "file_role", "canonical_target", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImportStagedRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_role", models.CharField(choices=[("metadata", "Metadata"), ("contrasts", "Contrasts")], max_length=30)),
                ("source_row_index", models.PositiveIntegerField()),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("import_batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staged_rows", to="profiling.importbatch")),
            ],
            options={
                "ordering": ["import_batch_id", "file_role", "source_row_index", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="importaliasmap",
            constraint=models.UniqueConstraint(fields=("import_batch", "file_role", "source_column"), name="unique_alias_source_per_batch_role"),
        ),
        migrations.AddConstraint(
            model_name="importstagedrow",
            constraint=models.UniqueConstraint(fields=("import_batch", "file_role", "source_row_index"), name="unique_staged_row_per_batch_role_index"),
        ),
    ]
