# Generated by Django 5.1.7 on 2026-07-30 19:49

import django.db.models.deletion
import profiling.models
from django.db import migrations, models


def populate_resource_keys(apps, schema_editor):
    StudyDataResource = apps.get_model("profiling", "StudyDataResource")
    for resource in StudyDataResource.objects.all().iterator():
        resource.resource_key = f"resource-{resource.pk}"
        resource.save(update_fields=["resource_key"])


def clear_generated_resource_keys(apps, schema_editor):
    StudyDataResource = apps.get_model("profiling", "StudyDataResource")
    StudyDataResource.objects.filter(resource_key__startswith="resource-").update(resource_key=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_databasebackup_and_more'),
        ('profiling', '0005_schema_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.CharField(choices=[('declared', 'Declared'), ('inferred', 'Inferred'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['child_resource_id', 'parent_resource_id'],
            },
        ),
        migrations.CreateModel(
            name='SequencingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(blank=True, max_length=50)),
                ('read_role', models.CharField(choices=[('R1', 'Read 1'), ('R2', 'Read 2'), ('I1', 'Index 1'), ('I2', 'Index 2'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('chunk', models.CharField(blank=True, max_length=50)),
                ('mapping_evidence', models.CharField(choices=[('declared', 'Declared'), ('inferred', 'Inferred'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ext', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['resource_id'],
            },
        ),
        migrations.CreateModel(
            name='SequencingLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_key', models.CharField(max_length=255)),
                ('preparation_method', models.CharField(blank=True, max_length=255)),
                ('ext', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sample_id', 'library_key', 'id'],
            },
        ),
        migrations.AddField(
            model_name='importbatch',
            name='applied_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='diff_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='manifest_schema_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='previous_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='profiling.importbatch'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_digest',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_directory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='tool_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studydataresource',
            name='resource_key',
            field=models.CharField(blank=True, default=profiling.models.default_resource_key, max_length=255, null=True),
        ),
        migrations.RunPython(populate_resource_keys, clear_generated_resource_keys),
        migrations.AddField(
            model_name='studywarehousemetadata',
            name='curation_status',
            field=models.CharField(choices=[('inventory', 'Inventory only'), ('metadata_curated', 'Metadata curated'), ('lineage_curated', 'Lineage curated')], default='inventory', max_length=30),
        ),
        migrations.AddField(
            model_name='studywarehousemetadata',
            name='lineage_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('partial', 'Partial'), ('complete', 'Complete')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('no_changes', 'No changes'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='planned', max_length=30),
        ),
        migrations.AlterField(
            model_name='profilingplatform',
            name='study_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('HTTr', 'High-throughput transcriptomics'), ('HTPP', 'High-throughput phenotypic profiling'), ('TGx', 'Toxicogenomics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studywarehousemetadata',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='profiling.profilingplatform'),
        ),
        migrations.AlterField(
            model_name='studywarehousemetadata',
            name='study_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('HTTr', 'High-throughput transcriptomics'), ('HTPP', 'High-throughput phenotypic profiling'), ('TGx', 'Toxicogenomics')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='studydataresource',
            constraint=models.UniqueConstraint(condition=models.Q(('study_metadata__isnull', False)), fields=('study_metadata', 'resource_key'), name='unique_resource_key_per_study'),
        ),
        migrations.AddConstraint(
            model_name='studydataresource',
            constraint=models.UniqueConstraint(condition=models.Q(('study_metadata__isnull', True)), fields=('resource_key',), name='unique_draft_resource_key'),
        ),
        migrations.AddField(
            model_name='resourcelineage',
            name='child_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_inputs', to='profiling.studydataresource'),
        ),
        migrations.AddField(
            model_name='resourcelineage',
            name='parent_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_outputs', to='profiling.studydataresource'),
        ),
        migrations.AddField(
            model_name='sequencingfile',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_file', to='profiling.studydataresource'),
        ),
        migrations.AddField(
            model_name='sequencingfile',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequencing_files', to='core.sample'),
        ),
        migrations.AddField(
            model_name='sequencingfile',
            name='sequencing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequencing_files', to='core.sequencingrun'),
        ),
        migrations.AddField(
            model_name='sequencinglibrary',
            name='assay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequencing_libraries', to='core.assay'),
        ),
        migrations.AddField(
            model_name='sequencinglibrary',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_libraries', to='core.sample'),
        ),
        migrations.AddField(
            model_name='sequencingfile',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='profiling.sequencinglibrary'),
        ),
        migrations.AddConstraint(
            model_name='resourcelineage',
            constraint=models.UniqueConstraint(fields=('parent_resource', 'child_resource'), name='unique_resource_lineage_edge'),
        ),
        migrations.AddConstraint(
            model_name='resourcelineage',
            constraint=models.CheckConstraint(condition=models.Q(('parent_resource', models.F('child_resource')), _negated=True), name='resource_lineage_not_self'),
        ),
        migrations.AddConstraint(
            model_name='sequencinglibrary',
            constraint=models.UniqueConstraint(fields=('sample', 'library_key'), name='unique_sequencing_library_per_sample'),
        ),
        migrations.AddIndex(
            model_name='sequencingfile',
            index=models.Index(fields=['sample', 'read_role'], name='seq_file_sample_read_idx'),
        ),
        migrations.AddIndex(
            model_name='sequencingfile',
            index=models.Index(fields=['sequencing_run', 'lane'], name='seq_file_run_lane_idx'),
        ),
    ]
