# Generated by Django 5.1.7 on 2026-07-30 19:50

import profiling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_resourcelineage_sequencingfile_sequencinglibrary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydataresource',
            name='resource_key',
            field=models.CharField(default=profiling.models.default_resource_key, max_length=255),
        ),
    ]
