# Generated by Django 5.1.7 on 2026-07-31 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_project_collaboration_key'),
        ('profiling', '0007_alter_studydataresource_resource_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studywarehousemetadata',
            name='primary_count_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_studies', to='profiling.studydataresource'),
        ),
        migrations.CreateModel(
            name='CountMatrixProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('raw_counts', 'Raw counts'), ('normalized_counts', 'Normalized counts'), ('abundance', 'Abundance'), ('other', 'Other')], max_length=30)),
                ('feature_id_kind', models.CharField(max_length=100)),
                ('annotation_source', models.CharField(max_length=255)),
                ('annotation_version', models.CharField(max_length=100)),
                ('feature_column', models.CharField(max_length=255)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('matrix_column_count', models.PositiveIntegerField(default=0)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], db_index=True, default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('schema_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='count_matrix_profile', to='profiling.studydataresource')),
            ],
            options={
                'ordering': ['resource_id'],
            },
        ),
        migrations.CreateModel(
            name='CountMatrixColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('ordinal', models.PositiveIntegerField()),
                ('samples', models.ManyToManyField(blank=True, related_name='count_matrix_columns', to='core.sample')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='profiling.countmatrixprofile')),
            ],
            options={
                'ordering': ['matrix_id', 'ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_ids', models.JSONField(default=list)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('compatibility_key', models.JSONField(blank=True, default=list)),
                ('source_checksums', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='queued', max_length=20)),
                ('output_path', models.TextField(blank=True)),
                ('output_filename', models.CharField(blank=True, max_length=255)),
                ('output_checksum', models.CharField(blank=True, max_length=64)),
                ('output_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('feature_count', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiling_data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='countmatrixprofile',
            index=models.Index(fields=['value_type', 'validation_status'], name='matrix_value_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='countmatrixcolumn',
            constraint=models.UniqueConstraint(fields=('matrix', 'original_name'), name='unique_matrix_column_name'),
        ),
        migrations.AddConstraint(
            model_name='countmatrixcolumn',
            constraint=models.UniqueConstraint(fields=('matrix', 'ordinal'), name='unique_matrix_column_ordinal'),
        ),
        migrations.AddIndex(
            model_name='dataexport',
            index=models.Index(fields=['requested_by', '-created_at'], name='export_user_created_idx'),
        ),
    ]
