# Generated by Django 5.1.7 on 2026-04-11 11:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_sample_fields_and_seed_study_models(apps, schema_editor):  # noqa: ARG001
    MetadataFieldDefinition = apps.get_model("core", "MetadataFieldDefinition")
    Sample = apps.get_model("core", "Sample")
    Study = apps.get_model("core", "Study")
    StudyConfig = apps.get_model("core", "StudyConfig")
    StudyMetadataFieldSelection = apps.get_model("core", "StudyMetadataFieldSelection")
    StudyMetadataMapping = apps.get_model("core", "StudyMetadataMapping")
    StudyOnboardingState = apps.get_model("core", "StudyOnboardingState")

    field_defaults = {
        "sample_ID": {"label": "Sample ID", "group": "Core", "description": "Unique sample identifier (no spaces).", "scope": "sample", "system_key": "sample_ID", "data_type": "string", "kind": "standard", "required": True, "is_core": True, "allow_null": False, "choices": [], "regex": r"^[a-zA-Z0-9-_]*$", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
        "sample_name": {"label": "Sample Name", "group": "Core", "description": "Human-readable sample name.", "scope": "sample", "system_key": "sample_name", "data_type": "string", "kind": "standard", "required": False, "is_core": False, "allow_null": True, "choices": [], "regex": "", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
        "technical_control": {"label": "Technical control", "group": "Core", "description": "True if this sample is a technical control.", "scope": "sample", "system_key": "technical_control", "data_type": "boolean", "kind": "standard", "required": False, "is_core": True, "allow_null": False, "choices": [], "regex": "", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
        "reference_rna": {"label": "Reference RNA", "group": "Core", "description": "True if this sample is reference RNA.", "scope": "sample", "system_key": "reference_rna", "data_type": "boolean", "kind": "standard", "required": False, "is_core": True, "allow_null": False, "choices": [], "regex": "", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
        "solvent_control": {"label": "Solvent control", "group": "Core", "description": "True if this sample is a solvent control.", "scope": "sample", "system_key": "solvent_control", "data_type": "boolean", "kind": "standard", "required": False, "is_core": True, "allow_null": False, "choices": [], "regex": "", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
        "group": {"label": "Group", "group": "Study design", "description": "Experimental group label.", "scope": "sample", "system_key": "group", "data_type": "string", "kind": "standard", "required": False, "is_core": False, "allow_null": True, "choices": [], "regex": "", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
        "chemical": {"label": "Chemical", "group": "Study design", "description": "Chemical short name.", "scope": "sample", "system_key": "chemical", "data_type": "string", "kind": "standard", "required": False, "is_core": False, "allow_null": True, "choices": [], "regex": "", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
        "chemical_longname": {"label": "Chemical Longname", "group": "Study design", "description": "Chemical long name.", "scope": "sample", "system_key": "chemical_longname", "data_type": "string", "kind": "standard", "required": False, "is_core": False, "allow_null": True, "choices": [], "regex": "", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
        "dose": {"label": "Dose", "group": "Study design", "description": "Dose amount.", "scope": "sample", "system_key": "dose", "data_type": "float", "kind": "standard", "required": False, "is_core": False, "allow_null": True, "choices": [], "regex": "", "min_value": 0, "max_value": None, "is_active": True, "auto_include_keys": []},
        "timepoint": {"label": "Timepoint", "group": "Study design", "description": "Custom typed metadata column.", "scope": "sample", "system_key": "timepoint", "data_type": "string", "kind": "custom", "required": False, "is_core": False, "allow_null": True, "choices": [], "regex": "", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
    }

    definitions = {}
    for key, defaults in field_defaults.items():
        definition, _ = MetadataFieldDefinition.objects.update_or_create(key=key, defaults=defaults)
        definitions[key] = definition

    for sample in Sample.objects.all().iterator():
        metadata = sample.metadata or {}
        if getattr(sample, "group", None):
            metadata["group"] = sample.group
        if getattr(sample, "chemical", None):
            metadata["chemical"] = sample.chemical
        if getattr(sample, "chemical_longname", None):
            metadata["chemical_longname"] = sample.chemical_longname
        if getattr(sample, "dose", None) is not None:
            metadata["dose"] = sample.dose
        sample.metadata = metadata
        sample.save(update_fields=["metadata"])

    default_config = {
        "common": {"projectdir": None, "metadata_file": "metadata.tsv", "contrasts_file": "contrasts.tsv", "project_description": None, "batch_var": None, "dose": "dose", "platform": "RNA-Seq", "nmr_threshold": 1000000, "write_additional_output": True, "celltype": "", "units": "", "biospyder_dbs": None, "biospyder_manifest_file": None, "solvent_control": "solvent_control"},
        "pipeline": {"genomedir": "/refs/genomes", "genome_filename": "", "annotation_filename": "", "genome_name": "", "sample_id": "sample_ID", "mode": "se", "threads": 8},
        "qc": {"clust_method": "spearman", "studywide_tree_height_cutoff": 0.1, "group_tree_height_cutoff": None, "dendro_color_by": "", "align_threshold": 0.95, "gini_cutoff": 0.99, "exp_groups": {}, "treatment_var": "", "collapse_replicates": False, "technical_control": "technical_control", "reference_rna": "reference_rna", "solvent_control": "solvent_control"},
        "deseq2": {"analysis_name": None, "species": None, "design": "", "intgroup_to_plot": [], "formula_override": None, "deseq_facet": None, "deseq_filter": None, "reports_facet": None, "reports_filter": None, "sortcol": None, "lenient_contrasts": False, "strict_contrasts": False, "exclude_samples": None, "exclude_groups": None, "include_only_column": None, "include_only_group": None, "cpus": 4, "run_pathway_analysis": True, "wikipathways_directory": None, "wikipathways_filename": None, "linear_fc_filter_DEGs": 1.5, "linear_fc_filter_biosets": 1.2, "nBestFeatures": 20, "nBest": 100, "nHeatmap": 50, "nHeatmapDEGs": 50, "cooks": False, "filter_gene_counts": False, "generate_main_report": True, "generate_stats_report": True, "generate_data_explorer_report": True, "generate_go_pathway_report": True, "generate_summary_report": True, "generate_runningfisher_report": False, "output_digits": 5, "parallel": False},
    }

    for study in Study.objects.all().iterator():
        state = StudyOnboardingState.objects.filter(study_id=study.id).first()
        mappings = state.mappings if state and isinstance(state.mappings, dict) else {}
        selected_contrasts = state.selected_contrasts if state else []

        StudyMetadataMapping.objects.get_or_create(
            study_id=study.id,
            defaults={
                "treatment_level_1": mappings.get("treatment_level_1", study.treatment_var or ""),
                "treatment_level_2": mappings.get("treatment_level_2", ""),
                "treatment_level_3": mappings.get("treatment_level_3", ""),
                "treatment_level_4": mappings.get("treatment_level_4", ""),
                "treatment_level_5": mappings.get("treatment_level_5", ""),
                "batch": mappings.get("batch", study.batch_var or ""),
                "pca_color": mappings.get("pca_color", ""),
                "pca_shape": mappings.get("pca_shape", ""),
                "pca_alpha": mappings.get("pca_alpha", ""),
                "clustering_group": mappings.get("clustering_group", ""),
                "report_faceting_group": mappings.get("report_faceting_group", ""),
                "selected_contrasts": selected_contrasts,
            },
        )

        config_payload = {
            "common": dict(default_config["common"]),
            "pipeline": dict(default_config["pipeline"]),
            "qc": dict(default_config["qc"]),
            "deseq2": dict(default_config["deseq2"]),
        }
        config_payload["common"]["celltype"] = study.celltype or ""
        config_payload["common"]["batch_var"] = study.batch_var
        config_payload["qc"]["treatment_var"] = study.treatment_var or ""
        config_payload["deseq2"]["species"] = study.species
        config_payload["deseq2"]["design"] = study.treatment_var or ""
        StudyConfig.objects.get_or_create(study_id=study.id, defaults=config_payload)

        columns = state.metadata_columns if state and isinstance(state.metadata_columns, list) and state.metadata_columns else []
        if not columns:
            columns = ["sample_ID", "technical_control", "reference_rna", "solvent_control"]
            if study.treatment_var:
                columns.append(study.treatment_var)
            if study.batch_var and study.batch_var not in columns:
                columns.append(study.batch_var)
        for core_key in ["sample_ID", "technical_control", "reference_rna", "solvent_control"]:
            if core_key not in columns:
                columns.insert(0, core_key)
        seen = []
        for key in columns:
            if key not in seen:
                seen.append(key)
        for index, key in enumerate(seen):
            definition = definitions.get(key)
            if definition is None:
                definition, _ = MetadataFieldDefinition.objects.get_or_create(
                    key=key,
                    defaults={"label": key.replace("_", " ").title(), "group": "Study design", "description": f"Migrated metadata field for {key}.", "scope": "sample", "system_key": key, "data_type": "string", "kind": "custom", "required": False, "is_core": False, "allow_null": True, "choices": [], "regex": "", "min_value": None, "max_value": None, "is_active": True, "auto_include_keys": []},
                )
                definitions[key] = definition
            StudyMetadataFieldSelection.objects.get_or_create(
                study_id=study.id,
                field_definition_id=definition.id,
                defaults={"required": bool(definition.is_core or definition.required), "sort_order": index, "is_active": True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_study_draft_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadatafielddefinition",
            name="allow_null",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="metadatafielddefinition",
            name="choices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="metadatafielddefinition",
            name="is_core",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="metadatafielddefinition",
            name="max_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadatafielddefinition",
            name="min_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadatafielddefinition",
            name="regex",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="metadatafielddefinition",
            name="scope",
            field=models.CharField(choices=[("sample", "Sample"), ("config", "Config")], default="sample", max_length=20),
        ),
        migrations.AddField(
            model_name="metadatafielddefinition",
            name="system_key",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sample",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="StudyConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("common", models.JSONField(blank=True, default=dict)),
                ("pipeline", models.JSONField(blank=True, default=dict)),
                ("qc", models.JSONField(blank=True, default=dict)),
                ("deseq2", models.JSONField(blank=True, default=dict)),
                ("study", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="config", to="core.study")),
            ],
            options={"ordering": ["study_id"]},
        ),
        migrations.CreateModel(
            name="StudyMetadataMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("treatment_level_1", models.CharField(blank=True, max_length=100)),
                ("treatment_level_2", models.CharField(blank=True, max_length=100)),
                ("treatment_level_3", models.CharField(blank=True, max_length=100)),
                ("treatment_level_4", models.CharField(blank=True, max_length=100)),
                ("treatment_level_5", models.CharField(blank=True, max_length=100)),
                ("batch", models.CharField(blank=True, max_length=100)),
                ("pca_color", models.CharField(blank=True, max_length=100)),
                ("pca_shape", models.CharField(blank=True, max_length=100)),
                ("pca_alpha", models.CharField(blank=True, max_length=100)),
                ("clustering_group", models.CharField(blank=True, max_length=100)),
                ("report_faceting_group", models.CharField(blank=True, max_length=100)),
                ("selected_contrasts", models.JSONField(blank=True, default=list)),
                ("study", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="metadata_mapping", to="core.study")),
            ],
            options={"ordering": ["study_id"]},
        ),
        migrations.CreateModel(
            name="StudyMetadataFieldSelection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("required", models.BooleanField(default=False)),
                ("column_label_override", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("field_definition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="study_selections", to="core.metadatafielddefinition")),
                ("study", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metadata_field_selections", to="core.study")),
            ],
            options={"ordering": ["study_id", "sort_order", "id"]},
        ),
        migrations.AddConstraint(
            model_name="studymetadatafieldselection",
            constraint=models.UniqueConstraint(fields=("study", "field_definition"), name="unique_field_selection_per_study"),
        ),
        migrations.RunPython(migrate_sample_fields_and_seed_study_models, migrations.RunPython.noop),
        migrations.RemoveField(model_name="sample", name="chemical"),
        migrations.RemoveField(model_name="sample", name="chemical_longname"),
        migrations.RemoveField(model_name="sample", name="dose"),
        migrations.RemoveField(model_name="sample", name="group"),
    ]
