# Generated by Django 5.1.7 on 2026-04-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_metadatafielddefinition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleplating',
            options={'ordering': ['sample_id'], 'verbose_name': 'sample plating', 'verbose_name_plural': 'sample plating records'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['id'], 'verbose_name': 'study', 'verbose_name_plural': 'studies'},
        ),
        migrations.AlterModelOptions(
            name='studyconfig',
            options={'ordering': ['study_id'], 'verbose_name': 'study configuration', 'verbose_name_plural': 'study configurations'},
        ),
        migrations.AlterModelOptions(
            name='studymetadatamapping',
            options={'ordering': ['study_id'], 'verbose_name': 'study metadata mapping', 'verbose_name_plural': 'study metadata mappings'},
        ),
        migrations.AlterModelOptions(
            name='studyonboardingstate',
            options={'ordering': ['study_id'], 'verbose_name': 'study onboarding state', 'verbose_name_plural': 'study onboarding states'},
        ),
    ]
