# Generated by Django 5.1.7 on 2026-04-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_sampleplating_options_alter_study_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneWorkItemSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_workspace_slug', models.CharField(blank=True, max_length=255)),
                ('plane_project_id', models.CharField(blank=True, max_length=255)),
                ('plane_work_item_id', models.CharField(blank=True, max_length=255)),
                ('plane_work_item_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plane_work_item_sync', to='core.study')),
            ],
            options={
                'verbose_name': 'Plane work item sync',
                'verbose_name_plural': 'Plane work item syncs',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
