# Generated by Django 5.1.7 on 2026-07-30 19:49

import core.models.intake
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_collaboration_keys(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    for project in Project.objects.all().iterator():
        project.collaboration_key = f"collaboration-{project.pk}"
        project.save(update_fields=["collaboration_key"])


def clear_generated_collaboration_keys(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    Project.objects.filter(collaboration_key__startswith="collaboration-").update(collaboration_key=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_schema_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('verification_status', models.CharField(choices=[('not_verified', 'Not verified'), ('running', 'Verification running'), ('passed', 'Verification passed'), ('failed', 'Verification failed')], default='not_verified', max_length=20)),
                ('path', models.TextField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('postgres_version', models.CharField(blank=True, max_length=100)),
                ('migration_snapshot', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='study',
            name='unique_study_per_project_metadata',
        ),
        migrations.AddField(
            model_name='project',
            name='collaboration_key',
            field=models.CharField(blank=True, default=core.models.intake.default_collaboration_key, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='date_run',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='flowcell_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='instrument_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='raw_data_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['status', '-created_at'], name='db_backup_status_created_idx'),
        ),
        migrations.RunPython(populate_collaboration_keys, clear_generated_collaboration_keys),
    ]
