# Generated by Django 5.1.7 on 2026-07-30 19:50

import core.models.intake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_databasebackup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaboration_key',
            field=models.CharField(default=core.models.intake.default_collaboration_key, max_length=255, unique=True),
        ),
    ]
